ci: hevay weapons

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,7 +49,13 @@ jobs:
 
       - name: Install npm Dependencies
         id: npm-ci
-        run: npm ci || (npm cache clean --force && npm i)
+        run: |
+          npm ci
+          if [ $? -ne 0 ]; then
+            echo "npm ci failed, running npm cache clean and npm install"
+            npm cache clean --force
+            npm install
+          fi
 
       - name: Install Playwright Dependencies
         if: steps.playwright-cache.outputs.cache-hit != 'true'
