fix(ci): master coverage calculation was broken due to artifacts conditions issue (#617)
* fix(ci): master coverage calculation was broken due to artifacts conditions issue

* fix(ci): enhance baseline availability checks for API and website coverage reports

* fix(ci): update coverage artifact names and permissions for baseline availability checks

* fix(ci): bad precondition for cross CI

* Wrong var assignment

* fix(ci): update artifact names to include CI change checks for website and API coverage reports

* fix(ci): correct logical grouping in artifact name conditions for website and API coverage reports

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,11 +31,12 @@ env:
   DEVOPS_DIRECTORY: devops
   DEVOPS_NODE_VERSION_FILE: devops/package.json
   DEVOPS_NODE_CACHE_PATH: devops/package-lock.json
-  WEBSITE_COVERAGE_ARTIFACT_NAME:
-  API_COVERAGE_ARTIFACT_NAME:
+  WEBSITE_COVERAGE_ARTIFACT_NAME_WF: website-coverage.${{ github.run_id }}
+  WEBSITE_COVERAGE_ARTIFACT_NAME_MASTER: website-coverage.master
+  API_COVERAGE_ARTIFACT_NAME_WF: api-coverage.${{ github.run_id }}
+  API_COVERAGE_ARTIFACT_NAME_MASTER: api-coverage.master
 
 jobs:
-  # ENV SETUP
   setup_env:
     name: Setup Environment Variables
     runs-on: ubuntu-latest
@@ -60,7 +61,27 @@ jobs:
         working-directory: ${{ env.WEBSITE_DIRECTORY }}
         run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package.json').devDependencies['@playwright/test'])")" >> $GITHUB_OUTPUT
 
-  # STARTING FLOW
+  determine_baseline_availability:
+    name: Determine Baseline Availability
+    permissions:
+      contents: read
+    runs-on: ubuntu-latest
+    outputs:
+      is_api_master_coverage_available: ${{ steps.master_api_coverage_report_exists.outputs.exists }}
+      is_website_master_coverage_available: ${{ steps.master_website_coverage_report_exists.outputs.exists }}
+    steps:
+      - name: Check for master API coverage report
+        id: master_api_coverage_report_exists
+        uses: LIT-Protocol/artifact-exists-action@v0
+        with:
+          name: ${{ env.API_COVERAGE_ARTIFACT_NAME_MASTER }}
+
+      - name: Check for master Website coverage report
+        id: master_website_coverage_report_exists
+        uses: LIT-Protocol/artifact-exists-action@v0
+        with:
+          name: ${{ env.WEBSITE_COVERAGE_ARTIFACT_NAME_MASTER }}
+
   determine_website_changes:
     name: Determine Website Changes
     needs: setup_env
@@ -184,8 +205,8 @@ jobs:
   website_e2e:
     name: Website CI
     runs-on: ubuntu-latest
-    needs: [setup_env, determine_website_changes, build_lcov_docker]
-    if: ${{ needs.determine_website_changes.outputs.module_changed == 'true' || needs.determine_website_changes.outputs.ci_changed == 'true' }}
+    needs: [setup_env, determine_website_changes, determine_baseline_availability, build_lcov_docker]
+    if: ${{ needs.determine_website_changes.outputs.module_changed == 'true' || needs.determine_website_changes.outputs.ci_changed == 'true' || needs.determine_baseline_availability.outputs.is_website_master_coverage_available == 'false' }}
     defaults:
       run:
         working-directory: ${{ env.WEBSITE_DIRECTORY }}
@@ -271,19 +292,19 @@ jobs:
         continue-on-error: true
         run: npm run coverage:merge
 
-      - name: Set Website Coverage Artifact Name
-        id: set-website-coverage-artifact-name
-        run: |
-          if [ "${{ github.ref }}" = "refs/heads/${{ github.event.repository.default_branch }}" ]; then
-            echo "WEBSITE_COVERAGE_ARTIFACT_NAME=website-coverage.master" >> $GITHUB_ENV
-          else
-            echo "WEBSITE_COVERAGE_ARTIFACT_NAME=website-coverage.${{ github.run_id }}" >> $GITHUB_ENV
-          fi
-
-      - name: Store Website Coverage Report
+      - name: Store Website Coverage Report (wf)
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ env.WEBSITE_COVERAGE_ARTIFACT_NAME }}
+          name: ${{ env.WEBSITE_COVERAGE_ARTIFACT_NAME_WF }}
+          path: ${{ env.WEBSITE_MERGED_COVERAGE_REPORT }}
+          retention-days: 400
+          overwrite: true
+
+      - name: Store Website Coverage Report (master)
+        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.WEBSITE_COVERAGE_ARTIFACT_NAME_MASTER }}
           path: ${{ env.WEBSITE_MERGED_COVERAGE_REPORT }}
           retention-days: 400
           overwrite: true
@@ -291,8 +312,8 @@ jobs:
   api_e2e:
     name: API CI
     runs-on: ubuntu-latest
-    needs: [setup_env, determine_api_changes]
-    if: ${{ needs.determine_api_changes.outputs.module_changed == 'true' || needs.determine_api_changes.outputs.ci_changed == 'true' }}
+    needs: [setup_env, determine_api_changes, determine_baseline_availability]
+    if: ${{ needs.determine_api_changes.outputs.module_changed == 'true' || needs.determine_api_changes.outputs.ci_changed == 'true' || needs.determine_baseline_availability.outputs.is_api_master_coverage_available == 'false' }}
     permissions:
       contents: read
 
@@ -393,34 +414,40 @@ jobs:
           retention-days: 30
           overwrite: true
 
-      - name: Set API Coverage Artifact Name
-        id: set-api-coverage-artifact-name
-        run: |
-          if [ "${{ github.ref }}" = "refs/heads/${{ github.event.repository.default_branch }}" ]; then
-            echo "API_COVERAGE_ARTIFACT_NAME=api-coverage.master" >> $GITHUB_ENV
-          else
-            echo "API_COVERAGE_ARTIFACT_NAME=api-coverage.${{ github.run_id }}" >> $GITHUB_ENV
-          fi
-
-      - name: Store API Coverage Report
+      - name: Store API Coverage Report (wf)
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ env.API_COVERAGE_ARTIFACT_NAME }}
+          name: ${{ env.API_COVERAGE_ARTIFACT_NAME_WF }}
           path: ${{ env.API_COVERAGE_REPORT }}
           retention-days: 400
           overwrite: true
 
-  # CLOSING FLOW
+      - name: Store API Coverage Report (master)
+        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.API_COVERAGE_ARTIFACT_NAME_MASTER }}
+          path: ${{ env.API_COVERAGE_REPORT }}
+          retention-days: 400
+          overwrite: true
+
   cross_module_ci:
     name: Cross Module CI
     runs-on: ubuntu-latest
     needs:
-      [determine_website_changes, determine_api_changes, website_performance, website_e2e, api_e2e, build_lcov_docker]
+      [
+        determine_website_changes,
+        determine_api_changes,
+        website_performance,
+        website_e2e,
+        api_e2e,
+        build_lcov_docker,
+        determine_baseline_availability,
+      ]
     if: ${{ always() }}
-
     steps:
-      - name: Verify each module CI status
-        id: verify_each_module_ci_status
+      - name: Check Prerequisites
+        id: check_prerequisites
         run: |
           WEBSITE_CHANGES_DETERMINATION_STATUS=$([ "${{ needs.determine_website_changes.result }}" = "success" ] && echo "success" || echo "failure") # Generated
           API_CHANGES_DETERMINATION_STATUS=$([ "${{ needs.determine_api_changes.result }}" = "success" ] && echo "success" || echo "failure") # Generated
@@ -434,9 +461,14 @@ jobs:
 
           WEBSITE_MODULE_CHANGED=$([ "${{ needs.determine_website_changes.outputs.module_changed }}" = "true" ] && echo "true" || echo "false") # Generated
           CI_CHANGED=$([ "${{ needs.determine_website_changes.outputs.ci_changed }}" = "true" ] && echo "true" || echo "false") # Generated
-          if [ "$WEBSITE_MODULE_CHANGED" = "true" ] || [ "$CI_CHANGED" = "true" ]; then
+          WEBSITE_MASTER_COVERAGE_AVAILABLE=$([ "${{ needs.determine_baseline_availability.outputs.is_website_master_coverage_available }}" = "true" ] && echo "true" || echo "false") # Generated
+          if [ "$WEBSITE_MODULE_CHANGED" = "true" ] || [ "$CI_CHANGED" = "true" ] || [ "$WEBSITE_MASTER_COVERAGE_AVAILABLE" = "false" ]; then
             E2E_STATUS=$([ "${{ needs.website_e2e.result }}" = "success" ] && echo "success" || echo "failure") # Generated
-            PERFORMANCE_STATUS=$([ "${{ needs.website_performance.result }}" = "success" ] && echo "success" || echo "failure") # Generated
+              PERFORMANCE_STATUS=skipped
+              # No need to run performance tests if only the master coverage is available but no changes were made to niether the website nor the CI
+              if [ "$WEBSITE_MODULE_CHANGED" = "true" ] || [ "$CI_CHANGED" = "true" ]; then
+                PERFORMANCE_STATUS=$([ "${{ needs.website_performance.result }}" = "success" ] && echo "success" || echo "failure") # Generated
+              fi
             if [ "$E2E_STATUS" = "failure" ] || [ "$PERFORMANCE_STATUS" = "failure" ]; then
               echo "Overall status: failure"
               exit 1
@@ -444,7 +476,8 @@ jobs:
           fi
 
           API_MODULE_CHANGED=$([ "${{ needs.determine_api_changes.outputs.module_changed }}" = "true" ] && echo "true" || echo "false") # Generated
-          if [ "$API_MODULE_CHANGED" = "true" ] || [ "$CI_CHANGED" = "true" ]; then
+          API_MASTER_COVERAGE_AVAILABLE=$([ "${{ needs.determine_baseline_availability.outputs.is_api_master_coverage_available }}" = "false" ] && echo "true" || echo "false") # Generated
+          if [ "$API_MODULE_CHANGED" = "true" ] || [ "$CI_CHANGED" = "true" ] || [ "$API_MASTER_COVERAGE_AVAILABLE" = "true" ]; then
             API_STATUS=$([ "${{ needs.api_e2e.result }}" = "success" ] && echo "success" || echo "failure") # Generated
             if [ "$API_STATUS" = "failure" ]; then
               echo "Overall status: failure"
@@ -463,13 +496,13 @@ jobs:
       - name: Restore Website Coverage Report
         uses: actions/download-artifact@v4
         with:
-          name: ${{ needs.determine_website_changes.outputs.module_changed == 'true' && format('website-coverage.{0}', github.run_id) || 'website-coverage.master' }}
+          name: ${{ ( needs.determine_website_changes.outputs.ci_changed == 'true' || needs.determine_website_changes.outputs.module_changed == 'true' ) && env.WEBSITE_COVERAGE_ARTIFACT_NAME_WF || env.WEBSITE_COVERAGE_ARTIFACT_NAME_MASTER }}
           path: ${{ env.WEBSITE_MERGED_COVERAGE_DIRECTORY }}
 
       - name: Restore API Coverage Report
         uses: actions/download-artifact@v4
         with:
-          name: ${{ needs.determine_api_changes.outputs.module_changed == 'true' && format('api-coverage.{0}', github.run_id) || 'api-coverage.master' }}
+          name: ${{ ( needs.determine_website_changes.outputs.ci_changed == 'true' || needs.determine_api_changes.outputs.module_changed == 'true' ) && env.API_COVERAGE_ARTIFACT_NAME_WF || env.API_COVERAGE_ARTIFACT_NAME_MASTER }}
           path: ${{ env.API_COVERAGE_DIRECTORY }}
 
       - name: Restore lcov Docker image
