fix(ci): update API CI workflow to include Node.js setup and caching for Playwright dependencies

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,6 +22,8 @@ env:
   API_DIRECTORY: web/api
   API_CARGO_FILE: web/api/Cargo.toml
   API_TESTS_DIRECTORY: web/api/tests
+  API_TESTS_NODE_VERSION_FILE: web/api/tests/package.json
+  API_TESTS_NODE_CACHE_PATH: web/api/tests/package-lock.json
   API_COVERAGE_REPORT: web/api/.coverage/lcov.info
   CROSS_MODULE_COVERAGE_REPORT: .coverage/lcov.info
 
@@ -271,7 +273,7 @@ jobs:
           retention-days: 30
           overwrite: true
 
-  api_tests:
+  api_e2e:
     name: API CI
     runs-on: ubuntu-latest
     needs: [setup_env, determine_api_changes]
@@ -304,6 +306,35 @@ jobs:
         id: lint
         working-directory: ${{ env.API_DIRECTORY }}
         run: cargo make lint
+
+      - name: Setup Node.js
+        id: setup-node
+        uses: actions/setup-node@v4
+        with:
+          node-version-file: ${{ env.API_TESTS_NODE_VERSION_FILE }}
+          cache-dependency-path: ${{ env.API_TESTS_NODE_CACHE_PATH }}
+          cache: npm
+
+      - name: Cache playwright binaries
+        uses: actions/cache@v4
+        id: playwright-cache
+        with:
+          path: |
+            ~/.cache/ms-playwright
+          key: ${{ runner.os }}-playwright-${{ needs.setup_env.outputs.WEBSITE_PLAYWRIGHT_VERSION }}
+
+      - name: Install npm Dependencies
+        id: npm_ci
+        working-directory: ${{ env.API_TESTS_DIRECTORY }}
+        run: |
+          npm ci --no-audit
+
+      - name: Install Playwright Dependencies
+        if: steps.playwright-cache.outputs.cache-hit != 'true'
+        working-directory: ${{ env.API_TESTS_DIRECTORY }}
+        run: |
+          npx playwright install --with-deps
+          npx playwright install-deps
 
       - name: E2E Test
         id: api-e2e
@@ -355,7 +386,7 @@ jobs:
   cross_module_ci:
     name: Cross Module CI
     runs-on: ubuntu-latest
-    needs: [determine_website_changes, determine_api_changes, website_performance, website_e2e, api_tests]
+    needs: [determine_website_changes, determine_api_changes, website_performance, website_e2e, api_e2e]
     if: ${{ always() }}
 
     steps:
@@ -385,7 +416,7 @@ jobs:
 
           API_MODULE_CHANGED=$([ "${{ needs.determine_api_changes.outputs.module_changed }}" = "true" ] && echo "true" || echo "false") # Generated
           if [ "$API_MODULE_CHANGED" = "true" ] || [ "$CI_CHANGED" = "true" ]; then
-            API_STATUS=$([ "${{ needs.api_tests.result }}" = "success" ] && echo "success" || echo "failure") # Generated
+            API_STATUS=$([ "${{ needs.api_e2e.result }}" = "success" ] && echo "success" || echo "failure") # Generated
             if [ "$API_STATUS" = "failure" ]; then
               echo "Overall status: failure"
               exit 1
