fix(ci): enhance baseline availability checks for API and website coverage reports

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -37,7 +37,6 @@ env:
   API_COVERAGE_ARTIFACT_NAME_MASTER:
 
 jobs:
-  # ENV SETUP
   setup_env:
     name: Setup Environment Variables
     runs-on: ubuntu-latest
@@ -62,7 +61,25 @@ jobs:
         working-directory: ${{ env.WEBSITE_DIRECTORY }}
         run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package.json').devDependencies['@playwright/test'])")" >> $GITHUB_OUTPUT
 
-  # STARTING FLOW
+  determine_baseline_availability:
+    name: Determine Baseline Availability
+    runs-on: ubuntu-latest
+    outputs:
+      is_api_master_coverage_available: ${{ steps.master_api_coverage_report_exists.outputs.exists }}
+      is_website_master_coverage_available: ${{ steps.master_website_coverage_report_exists.outputs.exists }}
+    steps:
+      - name: Check for master API coverage report
+        id: master_api_coverage_report_exists
+        uses: LIT-Protocol/artifact-exists-action@v0
+        with:
+          name: ${{ env.API_COVERAGE_ARTIFACT_NAME_MASTER }}
+
+      - name: Check for master Website coverage report
+        id: master_website_coverage_report_exists
+        uses: LIT-Protocol/artifact-exists-action@v0
+        with:
+          name: ${{ env.WEBSITE_COVERAGE_ARTIFACT_NAME_MASTER }}
+
   determine_website_changes:
     name: Determine Website Changes
     needs: setup_env
@@ -186,8 +203,8 @@ jobs:
   website_e2e:
     name: Website CI
     runs-on: ubuntu-latest
-    needs: [setup_env, determine_website_changes, build_lcov_docker]
-    if: ${{ needs.determine_website_changes.outputs.module_changed == 'true' || needs.determine_website_changes.outputs.ci_changed == 'true' }}
+    needs: [setup_env, determine_website_changes, determine_baseline_availability, build_lcov_docker]
+    if: ${{ needs.determine_website_changes.outputs.module_changed == 'true' || needs.determine_website_changes.outputs.ci_changed == 'true' || needs.determine_baseline_availability.outputs.is_website_master_coverage_available == 'false' }}
     defaults:
       run:
         working-directory: ${{ env.WEBSITE_DIRECTORY }}
@@ -299,8 +316,8 @@ jobs:
   api_e2e:
     name: API CI
     runs-on: ubuntu-latest
-    needs: [setup_env, determine_api_changes]
-    if: ${{ needs.determine_api_changes.outputs.module_changed == 'true' || needs.determine_api_changes.outputs.ci_changed == 'true' }}
+    needs: [setup_env, determine_api_changes, determine_baseline_availability]
+    if: ${{ needs.determine_api_changes.outputs.module_changed == 'true' || needs.determine_api_changes.outputs.ci_changed == 'true' || needs.determine_baseline_availability.outputs.is_api_master_coverage_available == 'false' }}
     permissions:
       contents: read
 
@@ -424,17 +441,24 @@ jobs:
           retention-days: 400
           overwrite: true
 
-  # CLOSING FLOW
   cross_module_ci:
     name: Cross Module CI
     runs-on: ubuntu-latest
     needs:
-      [determine_website_changes, determine_api_changes, website_performance, website_e2e, api_e2e, build_lcov_docker]
-    if: ${{ always() }}
+      [
+        determine_website_changes,
+        determine_api_changes,
+        website_performance,
+        website_e2e,
+        api_e2e,
+        build_lcov_docker,
+        determine_baseline_availability,
+      ]
+    if: ${{ always() && needs.api_e2e.result == 'success' && needs.website_performance.result == 'success' && needs.website_performance.result == 'skipped' }}
 
     steps:
-      - name: Verify each module CI status
-        id: verify_each_module_ci_status
+      - name: check prerequisites
+        id: check_prerequisites
         run: |
           WEBSITE_CHANGES_DETERMINATION_STATUS=$([ "${{ needs.determine_website_changes.result }}" = "success" ] && echo "success" || echo "failure") # Generated
           API_CHANGES_DETERMINATION_STATUS=$([ "${{ needs.determine_api_changes.result }}" = "success" ] && echo "success" || echo "failure") # Generated
@@ -448,9 +472,14 @@ jobs:
 
           WEBSITE_MODULE_CHANGED=$([ "${{ needs.determine_website_changes.outputs.module_changed }}" = "true" ] && echo "true" || echo "false") # Generated
           CI_CHANGED=$([ "${{ needs.determine_website_changes.outputs.ci_changed }}" = "true" ] && echo "true" || echo "false") # Generated
-          if [ "$WEBSITE_MODULE_CHANGED" = "true" ] || [ "$CI_CHANGED" = "true" ]; then
+          WEBSITE_MASTER_COVERAGE_AVAILABLE=$([ "${{ needs.determine_baseline_availability.outputs.is_website_master_coverage_available }}" = "true" ] && echo "true" || echo "false") # Generated
+          if [ "$WEBSITE_MODULE_CHANGED" = "true" ] || [ "$CI_CHANGED" = "true" ] || [ "$WEBSITE_MASTER_COVERAGE_AVAILABLE" = "false" ]; then
             E2E_STATUS=$([ "${{ needs.website_e2e.result }}" = "success" ] && echo "success" || echo "failure") # Generated
-            PERFORMANCE_STATUS=$([ "${{ needs.website_performance.result }}" = "success" ] && echo "success" || echo "failure") # Generated
+              PERFORMANCE_STATUS = "skipped"
+              # No need to run performance tests if only the master coverage is available but no changes were made to niether the website nor the CI
+              if [ "$WEBSITE_MODULE_CHANGED" = "true" ] || [ "$CI_CHANGED" = "true" ]; then
+                PERFORMANCE_STATUS=$([ "${{ needs.website_performance.result }}" = "success" ] && echo "success" || echo "failure") # Generated
+              fi
             if [ "$E2E_STATUS" = "failure" ] || [ "$PERFORMANCE_STATUS" = "failure" ]; then
               echo "Overall status: failure"
               exit 1
@@ -458,7 +487,8 @@ jobs:
           fi
 
           API_MODULE_CHANGED=$([ "${{ needs.determine_api_changes.outputs.module_changed }}" = "true" ] && echo "true" || echo "false") # Generated
-          if [ "$API_MODULE_CHANGED" = "true" ] || [ "$CI_CHANGED" = "true" ]; then
+          API_MASTER_COVERAGE_AVAILABLE=$([ "${{ needs.determine_baseline_availability.outputs.is_api_master_coverage_available }}" = "false" ] && echo "true" || echo "false") # Generated
+          if [ "$API_MODULE_CHANGED" = "true" ] || [ "$CI_CHANGED" = "true" ] || [ "$API_MASTER_COVERAGE_AVAILABLE" = "true" ]; then
             API_STATUS=$([ "${{ needs.api_e2e.result }}" = "success" ] && echo "success" || echo "failure") # Generated
             if [ "$API_STATUS" = "failure" ]; then
               echo "Overall status: failure"
