#23 try to change workflow path (#24)
* try to change workflow path

* back to original definition

* missed checkout

* add permission

* try to use a different way to trigger

* changes to the curl

* more options

* no need for if anymore

* catch curl response

* fix workflow name

* use PAT

* fix codacy issue

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -13,17 +13,45 @@ on:
         description: 'Workflow to run'
         required: true
         type: choice
+        default: 'ci.yml'
         options:
-        - CI Workflow
+        - 'ci.yml'
+      ref:
+        description: 'The branch or tag to run the workflow on'
+        required: true
+        default: 'master'
         # Add other workflow names here
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   run_selected_workflow:
     runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      pull-requests: write
     steps:
-      - name: Run CI Workflow
-        if: ${{ inputs.workflow_to_run == 'CI Workflow' }}
-        uses: .github/workflows/ci.yml
-
+      - name: Trigger specified workflow
+        id: trigger_workflow
+        env:
+          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          REPO: ${{ github.repository }}
+          INPUT_REF: ${{ github.event.inputs.ref }}
+          INPUT_WORKFLOW: ${{ github.event.inputs.workflow_to_run }}
+        run: |
+          response=$(curl -s -o response.txt -w "%{http_code}" -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ env.PERSONAL_ACCESS_TOKEN }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/${{ env.REPO }}/actions/workflows/${{ env.INPUT_WORKFLOW }}/dispatches \
+            -d '{"ref":"${{ env.INPUT_REF }}"}')
+          echo "HTTP_STATUS=$response" >> $GITHUB_ENV
+          cat response.txt
+      - name: Check curl response
+        run: |
+          if [ "${{ env.HTTP_STATUS }}" -eq 204 ]; then
+            echo "Workflow triggered successfully."
+          else
+            echo "Failed to trigger workflow. HTTP status: ${{ env.HTTP_STATUS }}"
+            exit 1
+          fi
         # Add more conditional steps for other workflows
