fix: update Codecov API call to handle pull request SHA and adjust status checks

diff --git a/.github/workflows/website-ci.yml b/.github/workflows/website-ci.yml
--- a/.github/workflows/website-ci.yml
+++ b/.github/workflows/website-ci.yml
@@ -287,12 +287,17 @@ jobs:
             RETRY_COUNT=0
             while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
               OWNER_REPO=(${GITHUB_REPOSITORY/\// })
-              CODECOV_JSON=$(curl -s -H "Authorization: Bearer ${{ secrets.CODECOV_API_TOKEN }}" "https://api.codecov.io/api/v2/github/${OWNER_REPO[0]}/repos/${OWNER_REPO[1]}/commits/${{ github.sha }}")
+              if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
+                GITHUB_SHA=$(cat $GITHUB_EVENT_PATH | jq -r .pull_request.head.sha)
+              else
+                GITHUB_SHA=${{ github.sha }}
+              fi
+              CODECOV_JSON=$(curl -s -H "Authorization: Bearer ${{ secrets.CODECOV_API_TOKEN }}" "https://api.codecov.io/api/v2/github/${OWNER_REPO[0]}/repos/${OWNER_REPO[1]}/commits/$GITHUB_SHA")
               echo "CODECOV_JSON: $CODECOV_JSON"
-              CODECOV_STATUS=$(echo "$CODECOV_JSON" | jq -r '.data.commit.state')
+              CODECOV_STATUS=$(echo "$CODECOV_JSON" | jq -r '.state')
               if [ "$CODECOV_STATUS" = "complete" ]; then
-                CODECOV_RESULT=$(echo "$CODECOV_JSON" | jq -r '.data.commit.result')
-                if [ "$CODECOV_RESULT" = "error" ]; then
+                CODECOV_RESULT=$(echo "$CODECOV_JSON" | jq -r '.ci_passed')
+                if [ "$CODECOV_RESULT" = "false" ]; then
                   echo "Codecov check failed"
                   echo "status=failure" >> $GITHUB_OUTPUT
                   exit 1
@@ -310,7 +315,13 @@ jobs:
             fi
           fi
 
-
+          # if [ "${{ needs.determine_changes.outputs.website_changed }}" = "true" ]; then
+          #   if [ "$PERFORMANCE_STATUS" = "failure" ]; then
+          #     echo "Overall status: failure"
+          #     echo "status=failure" >> $GITHUB_OUTPUT
+          #     exit 1
+          #   fi
+          # fi
 
           echo "Overall status: success"
           echo "status=success" >> $GITHUB_OUTPUT
